### ISSUE TITLE
Consider updating example to Rust 2018

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/lazy-static.rs#120]
In Rust2018 using extern crate, etc. is not necessary anymore.

**Comment by KodrAus** [comment]
Thanks @gnzlbg! We also need to explicitly `use lazy_static::lazy_static;` macro in the new edition to bring it into scope.

Would you like to submit a PR that makes this change?

**Comment by kami881** [comment]
Lazy rocket

**Comment by kami881** [comment]
Static lazy rocket

**Comment by ammgws** [comment]
Is this solved by #159, or is OP referring to the example on crates.io?

![image](https://user-images.githubusercontent.com/20397027/73084361-2a4df480-3f10-11ea-8ed2-668368478080.png)

**Comment by NickHackman** [comment]
I'd be happy to take this issue! It's a little past 2018, but better late than never. :+1: 

I'll link the PR to this issue when I'm done.

**Comment by LukasKalbertodt** [comment]
My bad, this is indeed already fixed, just not released on crates.io yet. Closing.

**Comment by yatesco** [comment]
Just a note that https://crates.io/crates/lazy_static still shows:

![image](https://user-images.githubusercontent.com/181469/102899443-cbb43200-4462-11eb-867c-519e5e025373.png)
